<template>
	<div>
		<banner></banner>
    <class-info :course="getClassCard"></class-info>
	</div>
</template>

<script type="text/javascript">
import ClassInfo from './class-info'
import Banner from './banner'
	export default {
		components: {
			ClassInfo,Banner
		},
		data () {
			return {
				getClassCard:[
            {
              typesTitle:"<em>实</em> / <em>战</em> / <em>推</em> / <em>荐</em>",
              ad:[],
              courseCard:[
                {
                  img:require('../assets/images/course-1-1.jpg'),
                  classTitle:'Python3入门与进阶',
                  courseLabel:[
                    'Python'
                  ],
                  courseCardInfo:[
                    '实战','初级'
                  ],
                  viewPeople:'288',
                  courseCardPrice:'￥299',
                  isFree:false,
                  courseStat:true
                },
                {
                  img:require('../assets/images/course-1-2.jpg'),
                  classTitle:'SSM到Spring Boot-从零开发校园商铺平台',
                  courseLabel:[
                    'Java','SpringBoot'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:true
                },
                {
                  img:require('../assets/images/course-1-3.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'1260',
                  courseCardPrice:'￥299.00',
                  isFree:false,
                  courseStat:false
                },
                {
                  img:require('../assets/images/course-1-4.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                },
                {
                  img:require('../assets/images/course-1-5.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                }
              ]
            },
            {
              typesTitle:"<em>新</em> / <em>上</em> / <em>好</em> / <em>课</em>",
              ad:[],
              courseCard:[
                {
                  img:require('../assets/images/course-2-1.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                },
                {
                  img:require('../assets/images/course-2-2.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                },
                {
                  img:require('../assets/images/course-2-3.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                },
                {
                  img:require('../assets/images/course-2-4.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                },
                {
                  img:require('../assets/images/course-2-5.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                },
                {
                  img:require('../assets/images/course-2-6.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                },
                {
                  img:require('../assets/images/course-2-7.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                },
                {
                  img:require('../assets/images/course-2-8.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                },
                {
                  img:require('../assets/images/course-2-9.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                },
                {
                  img:require('../assets/images/course-2-10.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                }
              ]
            },
            {
              typesTitle:"<em>新</em> / <em>手</em> / <em>入</em> / <em>门</em>",
              ad:[
                {
                  title:'大数据技术与实践训练营',
                  content:'一站式搞定大数据，给你更多工作机会，赢在起跑线！',
                  href:'',
                  bg:require('../assets/images/course-1-1.jpg'),
                },
                {
                  title:'AI和大数据时代的第一开发语言',
                  content:'Python逆袭成为最佳开发语言的掌门',
                  href:'',
                  bg:require('../assets/images/course-1-1.jpg'),
                }
              ],
              courseCard:[
                {
                  img:require('../assets/images/course-1-1.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                },
                {
                  img:require('../assets/images/course-1-2.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                },
                {
                  img:require('../assets/images/course-1-3.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                },
                {
                  img:require('../assets/images/course-1-4.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                },
                {
                  img:require('../assets/images/course-1-5.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                },
                {
                  img:require('../assets/images/course-1-1.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                },
                {
                  img:require('../assets/images/course-1-2.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                },
                {
                  img:require('../assets/images/course-1-3.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                },
                {
                  img:require('../assets/images/course-1-4.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                },
                {
                  img:require('../assets/images/course-1-5.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                }
              ]
            },
            {
              typesTitle:"<em>技</em> / <em>能</em> / <em>提</em> / <em>升</em>",
              ad:[
                {
                  title:'大数据技术与实践训练营',
                  content:'一站式搞定大数据，给你更多工作机会，赢在起跑线！',
                  href:'',
                  bg:require('../assets/images/course-1-1.jpg'),
                },
                {
                  title:'AI和大数据时代的第一开发语言',
                  content:'Python逆袭成为最佳开发语言的掌门',
                  href:'',
                  bg:require('../assets/images/course-1-1.jpg'),
                }
              ],
              courseCard:[
                {
                  img:require('../assets/images/course-1-1.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                },
                {
                  img:require('../assets/images/course-1-2.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                },
                {
                  img:require('../assets/images/course-1-3.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                },
                {
                  img:require('../assets/images/course-1-4.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                },
                {
                  img:require('../assets/images/course-1-5.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                },
                {
                  img:require('../assets/images/course-1-1.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                },
                {
                  img:require('../assets/images/course-1-2.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                },
                {
                  img:require('../assets/images/course-1-3.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                },
                {
                  img:require('../assets/images/course-1-4.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                },
                {
                  img:require('../assets/images/course-1-5.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                }
              ]
            },
            {
              typesTitle:"<em>前</em> / <em>沿</em> / <em>技</em> / <em>术</em>",
              ad:[
                {
                  title:'大数据技术与实践训练营',
                  content:'一站式搞定大数据，给你更多工作机会，赢在起跑线！',
                  href:'',
                  bg:require('../assets/images/course-1-1.jpg'),
                },
                {
                  title:'AI和大数据时代的第一开发语言',
                  content:'Python逆袭成为最佳开发语言的掌门',
                  href:'',
                  bg:require('../assets/images/course-1-1.jpg'),
                }
              ],
              courseCard:[
                {
                  img:require('../assets/images/course-1-1.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                },
                {
                  img:require('../assets/images/course-1-2.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                },
                {
                  img:require('../assets/images/course-1-3.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                },
                {
                  img:require('../assets/images/course-1-4.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                },
                {
                  img:require('../assets/images/course-1-5.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                },
                {
                  img:require('../assets/images/course-1-1.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                },
                {
                  img:require('../assets/images/course-1-2.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                },
                {
                  img:require('../assets/images/course-1-3.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                },
                {
                  img:require('../assets/images/course-1-4.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                },
                {
                  img:require('../assets/images/course-1-5.jpg'),
                  classTitle:'Vue+Django REST framework 打造生鲜电商项目',
                  courseLabel:[
                    'Python','Vue.js'
                  ],
                  courseCardInfo:[
                    '实战','中级'
                  ],
                  viewPeople:'211',
                  courseCardPrice:'￥288',
                  isFree:false,
                  courseStat:false
                }
              ]
            }
        ]
			}
		}
	}
</script>